---
name: 'Amplify Runner Action'
author: 'Amplify Security'
description: 'Runs security scanners against code and provides possible remediations automatically.'

runs:
  using: 'docker'
  image: 'docker://alpine:3.20'
