---
name: 'Amplify Runner Action'
author: 'Amplify Security'
description: 'Runs security scanners against code and provides possible remediations automatically.'

inputs:
  amplify-endpoint:
    description: URL of Amplify's API to request remediations from.
    default: 'https://api.amplify.security'

runs:
  using: 'docker'
  image: 'docker://amplifysecurity/runner:latest'
  env:
    AMPLIFY_ENDPOINT: ${{ inputs.amplify-endpoint }}
