:action-version: 0.2.0
= Amplify Runner Action

Github Action to run https://amplify.security[Amplify Security]'s CI Runner.

This action launches a container within your workflow that will authenticate with Amplify's public API, execute code scanners against your changes, and submit scan results to Amplify for generating remediations.

== Usage

For most users, you'll setup this action via the onboarding process when https://app.amplify.security/[signing up at Amplify].
You can however introduce this to existing workflows.
A minimal (incomplete) config with the necessary YAML is provided below.

[source,yaml,subs="attributes"]
----
---
on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  id-token: write

jobs:
  amplify-security-scan:
    runs-on: ubuntu-latest
    # external PRs do not have permission to request ID tokens
    if: !github.event.pull_request.head.repo.fork
    steps:
     - name: Run Amplify Security Scan
       uses: amplify-security/runner-action@v{action-version}
----

== What is Amplify Security?

Amplify Security is a cloud-native security platform that integrates industry leading security tools
into your development workflow and provides automtically generated code fixes for security vulnerabilities.
