---
# This should mostly be the production version of the workflow (i.e. Amplify is
# "installed" in this repo just like any other). It is otherwise not integrated
# with the contents of the repo itself (the CI workflow instead tests changes)
name: Amplify Security
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main", "develop"]

permissions:
  contents: read
  id-token: write

jobs:
  amplify-security-scan:
    name: Amplify Security Scan
    runs-on: ubuntu-latest
    if: (!github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Amplify Runner
        uses: amplify-security/runner-action@main
