---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # run at 17:00 UTC every weekday
    - cron: "0 17 * * 1,2,3,4,5"

permissions:
  contents: read
  id-token: write

jobs:
  test-action-lab:
    name: GitHub Actions Test (Lab)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Local Action (Lab)
        id: test-action
        uses: ./
        with:
          amplify-endpoint: https://api.lab.amplify.security

  test-action-prod:
    name: GitHub Actions Test (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Local Action
        id: test-action-prod
        uses: ./
