---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  test-action-lab:
    name: GitHub Actions Test (Lab)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

      - name: Test Local Action (Lab)
        id: test-action
        uses: ./
        with:
          amplify-endpoint: https://api.lab.amplify.security

  test-action-prod:
    name: GitHub Actions Test (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

      - name: Test Local Action
        id: test-action-prod
        uses: ./
